#! /bin/sh
DAEMON="aesdsocket"

case "$1" in
  start)
    echo 
        echo "Starting aesdsocket: "
        start-stop-daemon --start --name $DAEMON --startas "/usr/bin/$DAEMON" -- -d
        ;;
  stop)
        echo "Stopping aesdsocket: "
        start-stop-daemon --stop --name $DAEMON 
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

